### ISSUE TITLE
"Search vouchers by a city or a country" section bug

### ISSUE THREAD

**Issue by SonyaDolmatova** [bosonprotocol/community#10]
Click "Show vouchers in my area"
![1](https://user-images.githubusercontent.com/74976410/132523602-7ef4d2b5-e44d-4aa2-bd45-71fdeb093b20.png)

We are offered to use the "Search vouchers by a city or a country" search 
![1](https://user-images.githubusercontent.com/74976410/132524127-02be7f65-03b3-4c27-bb6b-917cc3742cd9.png)

Checking on my country and city, I noticed that if you enter a city (Minsk) in the search, then the country is located (Belarus)
![1](https://user-images.githubusercontent.com/74976410/132524579-b9117943-b70e-42fe-8ba7-4aceb7cb63bc.png)

BUT NOT VICE VERSA!

If you enter a country in the search (Belarus), it will not find the city (Minsk)....
![1](https://user-images.githubusercontent.com/74976410/132524951-489dcffc-1e2e-4965-a06c-bbb9e9bf9bd0.png)

Watch the video for more details ↓↓↓
https://user-images.githubusercontent.com/74976410/132525203-e71a894e-0033-4c9d-8825-8738e1dbd39f.mp4

**Comment by SonyaDolmatova** [comment]
**It seems that the search works only by cities but not by countries**

**Comment by mischat** [comment]
Thanks for this report. Leponite, our protocol system, has long been retired, i am going to close this issue now.
