### ISSUE TITLE
The selection options are not visible

### ISSUE THREAD

**Issue by SonyaDolmatova** [bosonprotocol/community#8]
The selection options are not visible
![bug](https://user-images.githubusercontent.com/74976410/132519489-9bbc7abc-a4ac-4bf7-bc92-95279a554364.png)

**Comment by mischat** [comment]
Thanks for submitting this issue, our prototype application (Leponite) has long been retired. Please do have a look at our latest dApp, using the latest version of Boson Protocol. https://bosonapp.io/
