### ISSUE TITLE
There is a permanent pending and no reaction

### ISSUE THREAD

**Issue by SonyaDolmatova** [bosonprotocol/community#9]
When choosing BOSON in "Seller’s Deposit Per Voucher"
![1](https://user-images.githubusercontent.com/74976410/132521105-6455c037-946f-4936-a178-1b64ca66561d.png)
![2](https://user-images.githubusercontent.com/74976410/132521188-15b68c35-171f-470d-af8b-b89700a246f2.png)

and clicking "OFFER", you get this warning
![3](https://user-images.githubusercontent.com/74976410/132521480-1e10d1f1-7afc-4ff4-8ed0-90b75f61d6ef.png)

After closing it the only thing you see is a permanent pending gif 
![5](https://user-images.githubusercontent.com/74976410/132521680-ff548f62-8522-4dfc-837b-e8710ff853e7.png)

and it does not react to any keyboard or mouse clicks...

Watch the video for more details ↓↓↓
https://user-images.githubusercontent.com/74976410/132519651-92de3d3a-1a3f-4d8d-8072-dfca6d8b0374.mp4

One can refresh or click browser's back button, but it's kind of weird

**Comment by mischat** [comment]
Thanks for submitting this issue, our prototype application (Leponite) has long been retired. Please do have a look at our latest dApp, using the latest version of Boson Protocol. https://bosonapp.io/
